version: '3.7'
services:
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=Petia
      - POSTGRES_PASSWORD=12345